### ISSUE TITLE
Can't find main module

### ISSUE THREAD

**Issue by darresan** [sLoPPydrive/PGLuminate#1]
When I run python pgluminate I recieve this error /usr/bin/python: can't find '__main__' module in 'pgluminate'. I also do pip install -r requirements.txt

Python version 2.7.9

Thanks in advance!

**Comment by sLoPPydrive** [comment]
That is strange. Please check if you...

1. ...are in the same directory as the `pgluminate.py` script
2. ...are using Python 2.7.x (you say you do but double check with `python -V`)
3. ...are actually executing `python pgluminate.py`

Never had a problem running this script.

**Comment by darresan** [comment]
Now It's working thanks! The problem was I comment the line of the proxy in the config.json file. 
I hope I help you too with this issue :)

**Comment by JoseLSegura** [comment]
In your instructions at README you suggest to use `python pgluminate`, that tries to find a `__main__.py` into the pgluminate module. I suggest to move the `pgluminate.py` to `pgluminate/__main__.py` or simply to correct the README.

**Comment by sLoPPydrive** [comment]
Just fixed the README. Thanks for pointing that out to me. :)
